hopprLabWebsite/Controllers/AnalyticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace hopprLabWebsite.Controllers
{
    public class AnalyticsController : Controller
    {
        // GET: Analytics
        public ActionResult Index()
        {
            return View();
        }
    }
}

hopprLabWebsite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace hopprLabWebsite.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

hopprLabWebsite/Controllers/IOTController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace hopprLabWebsite.Controllers
{
    public class IOTController : Controller
    {
        // GET: IOT
        public ActionResult Index()
        {
            return View();
        }
    }
}

hopprLabWebsite/Controllers/MobileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace hopprLabWebsite.Controllers
{
    public class MobileController : Controller
    {
        // GET: Mobile
        public ActionResult Index()
        {
            return View();
        }
    }
}

hopprLabWebsite/Controllers/WebController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace hopprLabWebsite.Controllers
{
    public class WebController : Controller
    {
        // GET: Web
        public ActionResult Index()
        {
            return View();
        }
    }
}

hopprLabWebsite/Views/Analytics/Index.cshtml
@{
    ViewBag.Title = "Analytics";
    Layout = null;
}

<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>@ViewBag.Title</title>
<link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon" />
<link rel="icon" href="~/favicon.ico" type="image/x-icon" />
<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
<script src="~/Scripts/modernizr-2.6.2.js"></script>
<script src="~/Scripts/scrollreveal.min.js"></script>
<link href="~/Content/animate.css" rel="stylesheet" />
<link href="~/Content/hover.css" rel="stylesheet" />
<div class="analytics-header"></div>

<nav id="nav" class="navbar customNav" data-spy="affix" data-offset-top="10" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                <span class="glyphicon glyphicon-chevron-down collapseicon"></span>
            </button>
            <a href="@Url.Action("Index","Home")"><img src="~/Images/hopprlab_logo.png" class="navbar-brand" /></a>
        </div>
        <div class="navbar-collapse collapse" id="navbar">
            <ul class="nav navbar-nav navbar-right nav-padding-top">
                <li><a href="@Url.Action("Index","Web")" class="pointer nav-title">WEB</a></li>
                <li><a href="@Url.Action("Index","Mobile")" class="pointer nav-title">MOBILE</a></li>
                <li><a href="@Url.Action("Index","Analytics")" class="pointer nav-title">ANALYTICS</a></li>
                <li><a href="@Url.Action("Index","IOT")" class="pointer nav-title">IoT</a></li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <div class="row" style="margin-top:10% !important;">
        <br /><br /><br /><br />
        <center>
            <div class="col-lg-6">
                <img src="~/Images/CompressedScreenshots/powerbi.png" class="web-ss1-size animated fadeIn" />
            </div>
            <br />
            <div class="col-lg-6">
                <br /><br /><br /><br />
                <div class="mobiledescription animated fadeIn">
                    <span class="title">Power BI</span>
                    <br />
                    <p class="description">
                        A suite of business analytics tools<br />
                        to analyze data and share insights.<br />
                        Monitor your business ad get answers quickly<br />
                        with rich dashboards available on every device.<br />
                        <br />
                        @*<button type="button" class="call-to-action-button" formtarget="_blank">Visit</button>*@
                        @*<img src="~/Images/CompressedScreenshots/ms_logo.png" width="150" height="70"/>
                        <img src="~/Images/CompressedScreenshots/ms_powerbi_logo.png" width="150" height="70" />
                        <br /><br />*@
                        <a href="https://login.microsoftonline.com/common/oauth2/authorize?client_id=871c010f-5e61-4fb1-83ac-98610a7e9110&response_mode=form_post&response_type=code+id_token&scope=openid+profile&state=OpenIdConnect.AuthenticationProperties%3dfvTohmFr2nrAoxMQ5-Qf0QlFxitmMG4W8rep5gHMxm3eNtXvrXIZOmafEjCm9Iv13eRRHFDiOlBeGqL9-vNNgeK1htXLAtfkvLPdI_bW6ScUzsN5Twyk-S-36w1KMVX8JanRqQ&nonce=636234984397107296.MzA4M2FhMzctMGYxNi00NTA3LTk0NTctNTk4ZjQ0YjYwYTYwNzI4MDE1OGMtODdkMy00YTEyLWJiYWMtOTA2M2YzMzk0OGI3&site_id=500453&redirect_uri=https%3a%2f%2fapp.powerbi.com%2f%3fnoSignUpCheck%3d1&post_logout_redirect_uri=https%3a%2f%2fapp.powerbi.com%2f%3fnoSignUpCheck%3d1&resource=https%3a%2f%2fanalysis.windows.net%2fpowerbi%2fapi&nux=1&msafed=0" class="removeunderline call-to-action-button hvr-ripple-out" target="_blank">Explore</a>
                    </p>
                </div>
            </div>
        </center>
    </div>
</div>

hopprLabWebsite/Views/Home/Index.cshtml
@{
    Layout = null;
    ViewBag.Title = "hopprLab";
}
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon"/>
    <link rel="icon" href="~/favicon.ico" type="image/x-icon" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/scrollreveal.min.js"></script>
    <link href="~/Content/hover.css" rel="stylesheet" />
</head>

<body>
    <div class="main-header-wrapper">
        <div class="main-header"></div>
    </div>
    <nav id="nav" class="navbar customNav navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                    <span class="glyphicon glyphicon-chevron-down collapseicon" style="padding-top:10px !important;"></span>
                </button>
                <a href="@Url.Action("Index","Home")"><img src="~/Images/hopprlab_logo.png" class="navbar-brand" /></a>
            </div>
            <div class="navbar-collapse collapse" id="navbar">
                <ul class="nav navbar-nav navbar-right nav-padding-top">
                    <li><a href="#web" class="pointer nav-title">WEB</a></li>
                    <li><a href="#mobile" class="pointer nav-title">MOBILE</a></li>
                    <li><a href="#analytics" class="pointer nav-title">ANALYTICS</a></li>
                    <li><a href="#iot" class="pointer nav-title">IoT</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">

        <div id="web">
            <div class="row centerVertically">
                <center>
                    <div class="col-lg-6">
                        <div class="webicon">
                            <img src="~/Images/web_icon.png" class="icon-size" />
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="webdescription breakingspace">
                            <span class="title">WEB</span>
                            <br /><br />
                            <p class="description">
                                 Offers wide range of timely applications<br />
                                 deployed and maintained in the cloud<br />
                                 that are accessible with your browser<br />
                                 anywhere from desktop to<br />
                                 mobile screens.<br />
                                <br />
                                <button class="call-to-action-button hvr-ripple-out" type="button" onclick="location.href='@Url.Action("Index", "Web")'">Explore<span class="glyphicon glyphicon-ar"></span></button>
                            </p>
                        </div>
                    </div>
                </center>
            </div>
        </div>

        <div id="mobile">
            <div class="row centerVertically">
                <center>
                    <div class="col-lg-6">
                        <div class="mobileicon">
                            <img src="~/Images/mobile_icon.png" class="icon-size" />
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="mobiledescription breakingspace">
                            <span class="title">MOBILE</span>
                            <br /><br />
                            <p class="description">
                                 Engage customers with simpler<br />
                                 and more efficient applications that will<br />
                                 provide similar services to those accessed on the web<br />
                                 while taking advantage of the unique features<br />
                                 a mobile device can offer.<br />
                                <br />
                                <button class="call-to-action-button hvr-ripple-out" type="button" onclick="location.href='@Url.Action("Index", "Mobile")'">Explore</button>
                            </p>
                        </div>
                    </div>
                </center>
            </div>
        </div>

        <div id="analytics">
            <div class="row centerVertically">
                <center>
                    <div class="col-lg-6">
                        <div class="analyticsicon">
                            <img src="~/Images/analytics_icon.png" class="icon-size" />
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="analyticsdescription breakingspace">
                            <span class="title">ANALYTICS</span>
                            <br /><br />
                            <p class="description">
                                Organize, visualize and analyze data to meet<br />
                                dashboards, reports and share insights<br />
                                that will measure your organization's<br />
                                performance.<br />
                                <br />
                                <button class="call-to-action-button hvr-ripple-out" type="button" onclick="location.href='@Url.Action("Index", "Analytics")'">Explore</button>
                            </p>
                        </div>
                    </div>
                </center>
            </div>
        </div>

        <div id="iot">
            <div class="row centerVertically">
                <center>
                    <div class="col-lg-6">
                        <div class="ioticon">
                            <img src="~/Images/iot_icon.png" class="icon-size" />
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="iotdescription breakingspace">
                            <span class="title">IoT</span>
                            <br /><br />
                            <p class="description">
                                System of physical things embedded with sensors,<br />
                                software, electronics and connectivity<br />
                                to allow better performance by exchanging data <br />
                                between interconnected devices.<br />
                                <br />
                                <button class="call-to-action-button hvr-ripple-out" type="button" onclick="location.href='@Url.Action("Index", "IOT")'">Explore</button>
                            </p>
                        </div>
                    </div>
                </center>
            </div>
        </div>
    </div>

    <a href="#" class="backtotop" data-toggle="tooltip" data-placement="top" title="Back to Top"></a>

    <footer>
        <hr />
            <center>
                <span>Copyright 2017 Asian Hospital and Medical Center. All rights reserved.</span>
            </center>
        <br />
    </footer>

<script src="~/Scripts/jquery-3.1.1.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>

    <script type="text/javascript">

    $("#nav ul li a[href^='#']").on('click', function (e) {
        e.preventDefault();
        var hash = this.hash;
        $('html, body').animate({
            scrollTop: $(hash).offset().top
        }, 300, function () {
            window.location.hash = hash;
        })
    });

    $('.navbar-collapse ul li a').click(function() {
        $('.navbar-toggle:visible').click();
    });

    window.sr = ScrollReveal();
    sr.reveal('.webicon', { duration: 300, delay: 150});
    sr.reveal('.mobileicon', { duration: 300, delay: 150});
    sr.reveal('.analyticsicon', { duration: 300, delay: 150 });
    sr.reveal('.ioticon', { duration: 300, delay: 150 });
    sr.reveal('.webdescription', { duration: 300, delay: 150 });
    sr.reveal('.mobiledescription', { duration: 300, delay: 150 });
    sr.reveal('.analyticsdescription', { duration: 300, delay: 150 });
    sr.reveal('.iotdescription', { duration: 300, delay: 150 });

    $(document).ready(function() {
        var scroll_start = 0;
        var start_change = $('.customNav');
        var offset = start_change.offset();
        $(document).scroll(function() { 
            scroll_start = $(this).scrollTop();
            if(scroll_start > offset.top) {
                $('.customNav').css('background-color', 'white');
            } else {
                $('.customNav').css('background-color', 'transparent');
            }
        });
    });

    jQuery(document).ready(function($){
    var offset = 200,
    offset_opacity = 1200,
    scroll_top_duration = 700,
    $back_to_top = $('.backtotop');

    $(window).scroll(function(){
        ( $(this).scrollTop() > offset ) ? $back_to_top.addClass('btn-is-visible') : $back_to_top.removeClass('btn-is-visible btn-fade-out');
        if( $(this).scrollTop() > offset_opacity ) { 
            $back_to_top.addClass('btn-fade-out');
        }
    });

    $back_to_top.on('click', function(event){
        event.preventDefault();
        $('body,html').animate({
            scrollTop: 0 ,
        }, scroll_top_duration
        );
    });
    });
    </script>
</body>
</html>

hopprLabWebsite/Views/IOT/Index.cshtml
@{
    ViewBag.Title = "IoT";
    Layout = null;
}

<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>@ViewBag.Title</title>
<link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon" />
<link rel="icon" href="~/favicon.ico" type="image/x-icon" />
<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
<script src="~/Scripts/modernizr-2.6.2.js"></script>
<script src="~/Scripts/scrollreveal.min.js"></script>
<link href="~/Content/animate.css" rel="stylesheet" />
<link href="~/Content/hover.css" rel="stylesheet" />
<div class="iot-header"></div>

<nav id="nav" class="navbar customNav" data-spy="affix" data-offset-top="10" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                <span class="glyphicon glyphicon-chevron-down collapseicon"></span>
            </button>
            <a href="@Url.Action("Index","Home")"><img src="~/Images/hopprlab_logo.png" class="navbar-brand" /></a>
        </div>
        <div class="navbar-collapse collapse" id="navbar">
            <ul class="nav navbar-nav navbar-right nav-padding-top">
                <li><a href="@Url.Action("Index","Web")" class="pointer nav-title">WEB</a></li>
                <li><a href="@Url.Action("Index","Mobile")" class="pointer nav-title">MOBILE</a></li>
                <li><a href="@Url.Action("Index","Analytics")" class="pointer nav-title">ANALYTICS</a></li>
                <li><a href="@Url.Action("Index","IOT")" class="pointer nav-title">IoT</a></li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <div class="row" style="margin-top:10% !important;">
        <br /><br /><br /><br /><br /><br />
        <center>
            <div class="col-lg-6">
                <br />
                <img src="~/Images/CompressedScreenshots/tempiot.png" class="web-ss1-size animated fadeIn" />
            </div>
            <br />
            <div class="col-lg-6">
                <br /><br /><br /><br />
                <div class="mobiledescription animated fadeIn">
                    <span class="title">Temperature and Humidty Monitor</span>
                    <br />
                    <p class="description">
                         Data communications between Particle Photon,<br />
                         Celsius Scale Thermometer and Percentage<br />
                         Scale Humidity Meter that results to the<br />
                         real-time monitoring of temperature and<br />
                         humidity over the internet using<br />
                         Ubidots IoT Platform.<br />
                        <br />
                        @*<img src="~/Images/CompressedScreenshots/aws_logo.jpg" width="150" height="70" />
                        <img src="~/Images/CompressedScreenshots/ubidots_logo.png" width="150" height="70" />
                        <img src="~/Images/CompressedScreenshots/particle_logo.png" width="160" height="60" />
                        <br /><br />*@
                        <a href="https://app.ubidots.com/ubi/public/getdashboard/page/AIs3ZDBzM3tQfisTDR4ae9GRR6A" class="removeunderline call-to-action-button hvr-ripple-out" target="_blank">Explore</a>
                    </p>
                </div>
            </div>
        </center>
    </div>
</div>

hopprLabWebsite/Views/Mobile/Index.cshtml
@{
    ViewBag.Title = "Mobile";
    Layout = null;
}

<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>@ViewBag.Title</title>
<link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon" />
<link rel="icon" href="~/favicon.ico" type="image/x-icon" />
<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
<script src="~/Scripts/modernizr-2.6.2.js"></script>
<script src="~/Scripts/scrollreveal.min.js"></script>
<link href="~/Content/animate.css" rel="stylesheet" />
<div class="mobile-header"></div>

<nav id="nav" class="navbar customNav" data-spy="affix" data-offset-top="10" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                <span class="glyphicon glyphicon-chevron-down collapseicon"></span>
            </button>
            <a href="@Url.Action("Index","Home")"><img src="~/Images/hopprlab_logo.png" class="navbar-brand" /></a>
        </div>
        <div class="navbar-collapse collapse" id="navbar">
            <ul class="nav navbar-nav navbar-right nav-padding-top">
                <li><a href="@Url.Action("Index","Web")" class="pointer nav-title">WEB</a></li>
                <li><a href="@Url.Action("Index","Mobile")" class="pointer nav-title">MOBILE</a></li>
                <li><a href="@Url.Action("Index","Analytics")" class="pointer nav-title">ANALYTICS</a></li>
                <li><a href="@Url.Action("Index","IOT")" class="pointer nav-title">IoT</a></li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <div class="row" style="margin-top:20% !important;">
        <br /><br />
        <center>
            <div class="col-lg-6">
                <img src="~/Images/CompressedScreenshots/eventmanagermobile.png" class="mobile-ss-size animated fadeIn" />
            </div>
            <div class="col-lg-6">
                <br /><br /><br /><br /><br />
                <div class="mobiledescription animated fadeIn">
                    <span class="title">Event Manager</span>
                    <br />
                    <p class="description">
                        Save your time and energy on the registration<br />
                        process and focus on interacting with your attendees<br />
                        during the event. Create the best registration<br />
                        experience with automated on-site check in.<br />
                        <br />
                        <img src="~/Images/CompressedScreenshots/csstore.png" width="150" height="70" />
                    </p>
                </div>
            </div>
        </center>
    </div>

    <div class="row" style="margin-top:5% !important;">
        <br /><br />
        <center>
            <div class="col-lg-6">
                <img src="~/Images/CompressedScreenshots/asianmobile.png" class="mobile-ss1-size animated fadeIn" />
            </div>
            <div class="col-lg-6">
                <br /><br /><br /><br /><br />
                <div class="mobiledescription animated fadeIn">
                    <span class="title">Asian Hospital</span>
                    <br />
                    <p class="description">
                        The official App from Asian Hospital and Medical Center.<br />
                        Feel right at home as we provide a turn by turn directions to<br />
                        the hospital. Get in touch at ease as you can now quickly<br />
                        contact us directly. Get to know us more and have a look on<br />
                        our unwavering world class quality care in our website.<br />
                        <br />
                        <img src="~/Images/appstore.png" width="150" height="50" />
                    </p>
                </div>
            </div>
        </center>
    </div>
</div>

<footer>
    <hr />
    <center>
        <span>Copyright 2017 Asian Hospital and Medical Center. All rights reserved.</span>
    </center>
    <br />
</footer>

hopprLabWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon" />
    <link rel="icon" href="~/favicon.ico" type="image/x-icon" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="~/Content/hover.css" rel="stylesheet" />
    <link href="~/Content/animate.css" rel="stylesheet" />
</head>
<body>
    <nav id="nav" class="navbar navbar-inverse navbar-fixed-top customNav">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                    <span class="glyphicon glyphicon-chevron-down collapseicon"></span>
                </button>
                <a href="@Url.Action("Index","Home")"><img src="~/Images/hopprlab_logo.png" class="navbar-brand" /></a>
            </div>
            <div class="navbar-collapse collapse" id="navbar">
                <ul class="nav navbar-nav navbar-right nav-padding-top">
                    <li><a href="@Url.Action("Index","Web")" class="pointer nav-title">WEB</a></li>
                    <li><a href="@Url.Action("Index","Mobile")" class="pointer nav-title">MOBILE</a></li>
                    <li><a href="@Url.Action("Index","Home")" class="pointer nav-title">ANALYTICS</a></li>
                    <li><a href="@Url.Action("Index","Home")" class="pointer nav-title">IoT</a></li>
                </ul>
            </div>
        </div>
    </nav>

        @RenderBody()
        
        @*<footer class="layout-footer">
            <div class="footer-div1"></div>
            <div class="footer-div2">*@
    <hr />
                <center>
                    <span>Copyright 2017 Asian Hospital and Medical Center. All rights reserved.</span>
                </center>
            @*</div>
            <div class="footer-div3"></div>
        </footer>*@


    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

hopprLabWebsite/Views/Web/Index.cshtml
@{
    ViewBag.Title = "Web";
    Layout = null;
}

<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>@ViewBag.Title</title>
<link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon" />
<link rel="icon" href="~/favicon.ico" type="image/x-icon" />
<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
<script src="~/Scripts/modernizr-2.6.2.js"></script>
<script src="~/Scripts/scrollreveal.min.js"></script>
<link href="~/Content/animate.css" rel="stylesheet" />
<link href="~/Content/hover.css" rel="stylesheet" />

<div class="web-header"></div>

<nav id="nav" class="navbar customNav" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                <span class="glyphicon glyphicon-chevron-down collapseicon"></span>
            </button>
            <a href="@Url.Action("Index","Home")"><img src="~/Images/hopprlab_logo.png" class="navbar-brand" /></a>
        </div>
        <div class="navbar-collapse collapse" id="navbar">
            <ul class="nav navbar-nav navbar-right nav-padding-top">
                <li><a href="@Url.Action("Index","Web")" class="pointer nav-title">WEB</a></li>
                <li><a href="@Url.Action("Index","Mobile")" class="pointer nav-title">MOBILE</a></li>
                <li><a href="@Url.Action("Index","Analytics")" class="pointer nav-title">ANALYTICS</a></li>
                <li><a href="@Url.Action("Index","IOT")" class="pointer nav-title">IoT</a></li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <div class="row" style="margin-top:10% !important;">
        <br /><br /><br /><br /><br /><br />
        <center>
            <div class="col-lg-6">
                <br />
                <img src="~/Images/CompressedScreenshots/eventmanagerweb.png" class="web-ss-size animated fadeIn" />
            </div>
            <br /><br /><br /><br />
            <div class="col-lg-6">
                <div class="mobiledescription animated fadeIn">
                    <span class="title">Event Manager</span>
                    <br />
                    <p class="description">
                         Create, organize and manage your events<br />
                         anytime and anywhere over the internet.<br />
                         Upload the list of your expected attendees<br />
                         in no time and generate report to track the<br />
                         registration from our mobile application.<br />
                        <br />
                        @*<button onclick="location.href='https://hopprlab.com/eventsmanager'" type="submit" class="call-to-action-button hvr-ripple-out" formtarget="_blank">Explore</button>*@
                        <a href="https://hopprlab.com/eventsmanager" class="removeunderline call-to-action-button hvr-ripple-out" target="_blank">Explore</a>
                    </p>
                </div>
            </div>
        </center>
    </div>

    <div class="row" style="margin-top:5% !important;">
        <br /><br /><br /><br /><br /><br />
        <center>
            <div class="col-lg-6">
                <img src="~/Images/CompressedScreenshots/ahmcportal.png" class="web-ss1-size animated fadeIn" />
            </div>
            <br />
            <div class="col-lg-6">
                <div class="mobiledescription animated fadeIn">
                    <br /><br /><br />
                    <span class="title">AHMC Portal</span>
                    <br /><br />
                    <p class="description">
                         The official portal of Asian Hospital and Medical Center.<br />
                         This allows acess to your health records and more over the internet.<br />
                        <br />
                        @*<button onclick="location.href='https://hopprlab.com/ahmcportal'" type="button" class="call-to-action-button hvr-ripple-out" formtarget="_blank">Visit</button>*@
                        <a href="https://hopprlab.com/ahmcportal" class="removeunderline call-to-action-button hvr-ripple-out" target="_blank">Explore</a>
                    </p>
                </div>
            </div>
        </center>
    </div>
</div>

<footer>
    <hr />
    <center>
        <span>Copyright 2017 Asian Hospital and Medical Center. All rights reserved.</span>
    </center>
    <br />
</footer>