hopprLabWebsitev2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace hopprLabWebsitev2.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

hopprLabWebsitev2/Controllers/SectionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace hopprLabWebsitev2.Controllers
{
    public class SectionsController : Controller
    {
        // GET: Section
        public ActionResult Web()
        {
            return View();
        }

        public ActionResult Mobile()
        {
            return View();
        }

        public ActionResult Analytics()
        {
            return View();
        }

        public ActionResult IoT()
        {
            return View();
        }
    }
}

hopprLabWebsitev2/Views/Home/Index.cshtml
@{
    ViewBag.Title = "hopprLab";
}

@*Image Banner with Text Animation*@
<div class="row noGutter">
    <div class="col-xs-12 col-lg-12">
        <div class="headerTextContainer">
            <center>
                <span style="line-height:70vh;">
                    <span class="headerText">Building apps through</span>
                    <span class="txt-rotate headerTextAnimate"
                          data-period="2000"
                          data-rotate='[ "CREATIVITY.", "INNOVATION.", "TECHNOLOGY." ]'>
                    </span>
                </span>
            </center>
        </div>
    </div>
</div>

<div class="headerBodyPadding"></div>

@*What is hopprlab section*@
<div class="container">

    <div class="row">
        <div class="col-lg-12">
            <span class="title ttle" style="text-align:left;color:black;">What is hopprlab?</span>
            <br /><br /> 
            <p class="description descri" style="color:#5e5e5e;">
                Inspired by the legacy of <a href="https://www.biography.com/people/grace-hopper-21406809" target="_blank" style="color:#1B996E;"><i>Grace Hopper</i></a>, hopprLab emerges as a bootstrapping initiative for <a href="http://www.asianhospital.com" target="_blank" style="color:#1B996E;"><i>Asian Hospital and Medical Center</i></a> to open the door of endless possibilities in building software and hardware that will eventually foster technology evolution. We, at hopprLab aspires to transform your concepts into actual lines of codes and to turn your ideas into reality. After all, no dream is too big and no idea is too small. Together, let us innovate and create something beyond boundaries.
</p>
        </div>
    </div>

</div>

<div class="headerBodyPadding"></div>

@*Body section (Web, Mobile, Analytic, IoT)*@
<div class="row">
    <div class="description-container">
        <div class="headerBodyPadding"></div>
        <div class="container">
            <center>
                <div class="row">
                    <div class="col-lg-6 col-md-6 web">
                        <div style="text-align:left;">
                            <img src="~/Content/Images/icons/web_icon_new.png" height="90" width="90" />
                            <span class="title" style="color:white;">Web</span>
                        </div>
                        <br>
                        <p class="description">
                            Offers wide range of timely applications deployed and maintained in the cloud that are accessible with your browser anywhere from desktop to mobile screens.
                        </p>
                        <br />
                        <div style="text-align:left;">
                            <a class="btn exploreBtn" href="@Url.Action("Web", "Sections")">Explore</a>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 paddingPerTitle mobile">
                        <div style="text-align:left;">
                            <img src="~/Content/Images/icons/mobile_icon_new.png" height="90" width="70" />
                            <span class="title" style="color:white;">Mobile</span>
                        </div>
                        <br />
                        <p class="description">
                            Engage customers with simpler and more efficient applications that will provide similar services to those accessed on the web while taking advantage of the unique features a mobile device can offer.
                        </p>
                        <br />
                        <div style="text-align:left;">
                            <a class="btn exploreBtn" href="@Url.Action("Mobile", "Sections")">Explore</a>
                        </div>
                    </div>
                </div>
                <div class="paddingPerRow"></div>
                <div class="row">
                    <div class="col-lg-6 col-md-6 paddingPerTitle analytics">
                        <div style="text-align:left;">
                            <img src="~/Content/Images/icons/analytics_icon_new.png" height="90" width="90" />
                            <span class="title" style="color:white;">Analytics</span>
                        </div>
                        <br />
                        <p class="description">
                            Organize, visualize and analyze data to meet dashboards, reports and share insights that will measure your organization's performance.
                        </p>
                        <br />
                        <div style="text-align:left;">
                            <a class="btn exploreBtn" href="@Url.Action("Analytics","Sections")">Explore</a>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 paddingPerTitle iot">
                        <div style="text-align:left;">
                            <img src="~/Content/Images/icons/iot_icon_new.png" height="90" width="90" />
                            <span class="title" style="color:white;">IoT</span>
                        </div>
                        <br />
                        <p class="description">
                            System of physical things embedded with sensors, software, electronics and connectivity to allow better performance by exchanging data between interconnected devices.
                        </p>
                        <br />
                        <div style="text-align:left;">
                            <a class="btn exploreBtn" href="@Url.Action("IoT", "Sections")">Explore</a>
                        </div>
                    </div>
                </div>
            </center>
        </div>
        <div class="headerBodyPadding"></div>
    </div>
</div>
        
@*People behind section*@
<div class="row noGutter">
    <div class="col-xs-12 col-lg-12">
        <div class="peopleBehindContainer">
            <center>
                <div style="width:100%; height:50vh; background-color:rgba(109,197,144, 0.4); position:relative; top:25vh;" class="peopleBehind">
                    <div class="sliderWrapper">
                        <div id="slider" style="cursor:-webkit-grab;">
                            <div class="box">
                                <center>
                                    <img src="~/Content/Images/developers/sir.png" />
                                    <p class="sliderText">Darren Blanco</p>
                                    <h5 class="slidersubText">Team Lead</h5>
                                </center>
                            </div>
                            <div class="box">
                                <center>
                                    <img src="~/Content/Images/developers/nino.png" />
                                    <p class="sliderText">Niño Venzon</p>
                                    <h5 class="slidersubText">IoT and Cloud Infrastructure Administrator</h5>
                                </center>
                            </div>
                            <div class="box">
                                <center>
                                    <img src="~/Content/Images/developers/stven.png" />
                                    <p class="sliderText">Steven Rhey Balan</p>
                                    <h5 class="slidersubText">iOS Mobile Developer</h5>
                                </center>
                            </div>
                            <div class="box">
                                <center>
                                    <img src="~/Content/Images/developers/jel.png" />
                                    <p class="sliderText">Erjel Labetoria</p>
                                    <h5 class="slidersubText">Web / API Developer</h5>
                                </center>
                            </div>
                            <div class="box">
                                <center>
                                    <img src="~/Content/Images/developers/cess.png" />
                                    <p class="sliderText">Princess Joy Esmenda</p>
                                    <h5 class="slidersubText">Web / Analytics Developer</h5>
                                </center>
                            </div>
                            <div class="box">
                                <center>
                                    <img src="~/Content/Images/developers/rap.png" />
                                    <p class="sliderText">Reynard Paco</p>
                                    <h5 class="slidersubText">Graphics and Multimedia Artist</h5>
                                </center>
                            </div>
                            <div class="box">
                                <center>
                                    <img src="~/Content/Images/developers/dia.png" />
                                    <p class="sliderText">Dia Loraine Ann Aguilar</p>
                                    <h5 class="slidersubText">Web / Analytics Developer</h5>
                                </center>
                            </div>
                        </div>
                    </div>
                </div>
            </center>
        </div>
    </div>
</div>





        

    

  

hopprLabWebsitev2/Views/Sections/Analytics.cshtml
@{
    ViewBag.Title = "Analytics";
}

<div class="row noGutter">
    <div class="col-xs-12 col-lg-12">
        <div class="analyticsContainer">
            <center>
                <span style="line-height:70vh;">
                    <span class="headerText"></span>
                </span>
            </center>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-lg-12" style="padding-top:80px;padding-bottom:80px;">
            <center>
                <span class="headerTitle">OUR WORK</span>
            </center>
        </div>
    </div>
</div>

<div class="container" style="padding-bottom: 80px;">
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 paddingBottom">
            @*<a href="#">*@
                <div class="wrapper">
                    <img src="~/Content/Images/our_work/powerbi.jpg" class="img-responsive imageOne" />
                    <div class="wrapper-overlay hidden-md hidden-sm hidden-xs">
                        <center>
                            <span class="wrapper-overlay-text">Power BI</span>
                            <p class="wrapper-overlay-description" style="padding-top:30px;">
                                A suite of business analytics tools to analyze data and share insights. Monitor your business ad get answers quickly with rich dashboards available on every device.
                            </p>
                        </center>
                    </div>
                    <div class="visible-md visible-sm visible-xs">
                        <br />
                        <center>
                            <span class="wrapper-overlay-text" style="color:black;">Power BI</span><br />
                            <span class="wrapper-overlay-description" style="color:black;font-size:12px;">
                                A suite of business analytics tools to analyze data and share insights. Monitor your business ad get answers quickly with rich dashboards available on every device.
                            </span>
                        </center>
                    </div>
                </div>
            @*</a>*@
        </div>
    </div>
</div>

hopprLabWebsitev2/Views/Sections/IoT.cshtml
@{
    ViewBag.Title = "IoT";
}

<div class="row noGutter">
    <div class="col-xs-12 col-lg-12">
        <div class="iotContainer">
            <center>
                <span style="line-height:70vh;">
                    <span class="headerText"></span>
                </span>
            </center>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-lg-12" style="padding-top:80px;padding-bottom:80px;">
            <center>
                <span class="headerTitle">OUR WORK</span>
            </center>
        </div>
    </div>
</div>

<div class="container" style="padding-bottom: 80px;">
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 paddingBottom">
            <a href="http://asianhospital.iot.ubidots.com/ubi/public/getdashboard/page/8o-Rn1ZxE6ip_9at5NOfW-1thUA" target="_blank">
                <div class="wrapper">
                    <img src="~/Content/Images/our_work/iot.jpg" class="img-responsive imageOne" />
                    <div class="wrapper-overlay hidden-md hidden-sm hidden-xs">
                        <center>
                            <span class="wrapper-overlay-text">Temperature Monitor</span>
                            <p class="wrapper-overlay-description" style="padding-top:30px;">
                                Real-time monitoring of temperature and humidity over the internet using Ubidots IoT Platform.
                            </p>
                        </center>
                    </div>
                    <div class="visible-md visible-sm visible-xs">
                        <br />
                        <center>
                            <span class="wrapper-overlay-text" style="color:black;">Temperature Monitor</span><br />
                            <span class="wrapper-overlay-description" style="color:black;font-size:12px;">
                                Real-time monitoring of temperature and humidity over the internet using Ubidots IoT Platform.
                            </span>
                        </center>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>

hopprLabWebsitev2/Views/Sections/Mobile.cshtml
@{
    ViewBag.Title = "Mobile";
}

<div class="row noGutter">
    <div class="col-xs-12 col-lg-12">
        <div class="mobileContainer">
            <center>
                <span style="line-height:70vh;">
                    <span class="headerText" style="color:white;"></span>
                </span>
            </center>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-lg-12" style="padding-top:80px;padding-bottom:80px;">
            <center>
                <span class="headerTitle">OUR WORK</span>
            </center>
        </div>
    </div>
</div>

<div class="container" style="padding-bottom: 80px;">
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 paddingBottom">
            <div class="wrapper">
                <img src="~/Content/Images/our_work/eventmanagermobile.jpg" class="img-responsive imageOne" />
                <div class="wrapper-overlay hidden-md hidden-sm hidden-xs">
                    <center>
                        <span class="wrapper-overlay-text">Event Manager</span>
                        <p class="wrapper-overlay-description" style="padding-top:30px;">
                            Create the best registration experience with automated on-site check in.
                        </p>
                    </center>
                </div>
                <div class="visible-md visible-sm visible-xs">
                    <br />
                    <center>
                        <span class="wrapper-overlay-text" style="color:black;">Event Manager</span><br />
                        <span class="wrapper-overlay-description" style="color:black;font-size:12px;">
                            Create the best registration experience with automated on-site check in.
                        </span>
                    </center>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 paddingBottom">
            <div class="wrapper">
                <img src="~/Content/Images/our_work/ahmcapp.jpg" class="img-responsive imageOne" />
                <div class="wrapper-overlay hidden-md hidden-sm hidden-xs">
                    <center>
                        <span class="wrapper-overlay-text">Asian Hospital App</span>
                        <p class="wrapper-overlay-description" style="padding-top:30px;">
                            Feel right at home as we provide a turn by turn directions to the hospital. Get in touch at ease as you can now quickly contact us directly. Get to know us more and have a look on our unwavering world class quality care in our website.
                        </p>
                    </center>
                </div>
                <div class="visible-md visible-sm visible-xs">
                    <br />
                    <center>
                        <span class="wrapper-overlay-text" style="color:black;">Asian Hospital App</span><br />
                        <span class="wrapper-overlay-description" style="color:black;font-size:12px;">
                            Feel right at home as we provide a turn by turn directions to the hospital. Get in touch at ease as you can now quickly contact us directly. Get to know us more and have a look on our unwavering world class quality care in our website.
                        </span>
                    </center>
                </div>
            </div>
        </div>
    </div>
</div>

hopprLabWebsitev2/Views/Sections/Web.cshtml
@{
    ViewBag.Title = "Web";
}

<div class="row noGutter">
    <div class="col-xs-12 col-lg-12">
        <div class="webContainer">
            <center>
                <span style="line-height:70vh;">
                    <span class="headerText" style="color:white;"></span>
                </span>
            </center>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-lg-12" style="padding-top:80px;padding-bottom:80px;">
            <center>
                <span class="headerTitle">OUR WORK</span>
            </center>
        </div>
    </div>
</div>

<div class="container" style="padding-bottom: 80px;">
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 paddingBottom">
            <a href="https://hopprlab.com/eventsmanager" target="_blank">
                <div class="wrapper">
                    <img src="~/Content/Images/our_work/eventmanager.jpg" class="img-responsive imageOne" />
                    <div class="wrapper-overlay hidden-md hidden-sm hidden-xs">
                        <center>
                            <span class="wrapper-overlay-text">Event Manager</span>
                            <p class="wrapper-overlay-description" style="padding-top:30px;">
                                Create, organize and manage your events anytime and anywhere over the internet.
                            </p>
                        </center>
                    </div>
                    <div class="visible-md visible-sm visible-xs">
                        <br />
                        <center>
                            <span class="wrapper-overlay-text" style="color:black;">Event Manager</span><br />
                            <span class="wrapper-overlay-description" style="color:black;font-size:12px;">
                                Create, organize and manage your events anytime and anywhere over the internet.
                            </span>
                        </center>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 paddingBottom">
            <a href="https://hopprlab.com/portal" target="_blank">
                <div class="wrapper">
                    <img src="~/Content/Images/our_work/portal.jpg" class="img-responsive imageOne" />
                    <div class="wrapper-overlay hidden-md hidden-sm hidden-xs">
                        <center>
                            <span class="wrapper-overlay-text">AHMC Portal</span>
                            <p class="wrapper-overlay-description" style="padding-top:30px;">
                                The official portal of Asian Hospital and Medical Center which allows acess to your health records and more over the internet.
                            </p>
                        </center>
                    </div>
                    <div class="visible-md visible-sm visible-xs">
                        <br />
                        <center>
                            <span class="wrapper-overlay-text" style="color:black;">AHMC Portal</span><br />
                            <span class="wrapper-overlay-description" style="color:black;font-size:12px;">
                                The official portal of Asian Hospital and Medical Center which allows acess to your health records and more over the internet.
                            </span>
                        </center>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <div class="wrapper">
                <img src="~/Content/Images/our_work/comingsoon.jpg" class="img-responsive imageOne" />
                <div class="wrapper-overlay hidden-md hidden-sm hidden-xs">
                    <center>
                        <span class="wrapper-overlay-text">CMS</span>
                        <p class="wrapper-overlay-description" style="padding-top:30px;">
                            Upload and manage your corporate contracts and agreements digitally in one place.
                        </p>
                    </center>
                </div>
                <div class="visible-md visible-sm visible-xs">
                    <br />
                    <center>
                        <span class="wrapper-overlay-text" style="color:black;">CMS</span><br />
                        <span class="wrapper-overlay-description" style="color:black;font-size:12px;">
                            Upload and manage your corporate contracts and agreements digitally in one place.
                        </span>
                    </center>
                </div>
            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
            <div class="wrapper">
                <img src="~/Content/Images/our_work/comingsoon.jpg" class="img-responsive imageOne" />
                <div class="wrapper-overlay hidden-md hidden-sm hidden-xs">
                    <center>
                        <span class="wrapper-overlay-text">IR</span>
                        <p class="wrapper-overlay-description" style="padding-top:30px;">
                            Report all variance, issues and complaints encountered with patients and in work area.
                        </p>
                    </center>
                </div>
                <div class="visible-md visible-sm visible-xs">
                    <br />
                    <center>
                        <span class="wrapper-overlay-text" style="color:black;">IR</span><br />
                        <span class="wrapper-overlay-description" style="color:black;font-size:12px;">
                            Report all variance, issues and complaints encountered with patients and in work area.
                        </span>
                    </center>
                </div>
            </div>
        </div>
    </div>
</div>

hopprLabWebsitev2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon" />
     @Styles.Render("~/content/css")
</head>
<body>

@*navbar & sidebar*@
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" onclick="openSidebar()">
                <span class="fa fa-bars" style="color:#1B996E;font-size:20px;"></span>
            </button>
            @Html.ActionLink("hopprLab", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right" style="cursor:pointer;">
                <li><a href="@Url.Action("Web","Sections")">Web</a></li>
                <li><a href="@Url.Action("Mobile","Sections")">Mobile</a></li>
                <li><a href="@Url.Action("Analytics","Sections")">Analytics</a></li>
                <li><a href="@Url.Action("IoT","Sections")">IoT</a></li>
                @*<li style="padding-left:40px;"><a href="@Url.Action("","")">Developers</a></li>*@
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Developers&nbsp;<span class="fa fa-angle-down"></span></a>
                    <ul class="dropdown-menu" style="min-width:135px !important;padding-top:10px;padding-bottom:10px;">
                        <li><a href="https://hopprlab.com/openapi" style="font-size:16px;" target="_blank">Open API</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <div id="sidebar" class="sidebar hidden-lg hidden-md">
            <span class="closeBtn" onclick="closeSidebar()" style="cursor:pointer;">&times;</span>
            <span class="closeBtn" onclick="closeSidebar()" style="cursor:pointer;">&times;</span>
            <div class="sidebarTextWrapper">
                <center>
                    <div class="sidebarTextPadding"><a href="@Url.Action("Web","Sections")"><span class="sidebarText">Web</span></a></div>
                    <div class="sidebarTextPadding"><a href="@Url.Action("Mobile","Sections")"><span class="sidebarText">Mobile</span></a></div>
                    <div class="sidebarTextPadding"><a href="@Url.Action("Analytics","Sections")"><span class="sidebarText">Analytics</span></a></div>
                    <div class="sidebarTextPadding"><a href="@Url.Action("IoT","Sections")"><span class="sidebarText">IoT</span></a></div>
                </center>
            </div>
            <div class="sidebarFooterTextWrapper">
                <center>
                    <div class="sidebarFooterTextPadding">
                        <a data-toggle="collapse" data-target="#dev" href="#dev"><span class="sidebarFooterText">Developers</span></a>
                        <div id="dev" class="collapse">
                            <a href="https://hopprlab.com/openapi" target="_blank"><span class="sidebarFooterText" style="font-size:15px;">Open API</span></a>
                        </div>
                    </div>
                </center>
            </div>
        </div>
    </div>
</div>

@*Body*@
<div class="container-fluid">
    @RenderBody()

    <div class="row noGutter">
        <div class="col-lg-12">
            <div class="footerWrapper">
                <div style="text-align:center;line-height:8vh;">
                    <i class="fa fa-copyright"></i>&nbsp;<span class="footerContent">hopprLab 2017 | info@hopprlab.com</span>
                    @*<i class="fa fa-facebook-square"></i>&nbsp;<i class="fa fa-twitter-square"></i>&nbsp;<i class="fa fa-instagram"></i>*@
                </div>
            </div>
        </div>
    </div>
</div>

@*Footer Section*@
  
</body>
</html>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/modernizr")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/scripts")